theme: jekyll-theme-slate
title: [SNOdar Snow Measurement]
description: [A new high-accuracy , high-tech snow depth sensor + data logger ,  accessible and configurable via BLE]
show_downloads: [true]
